const state={
  route:'landing', mode:'employee', points:220,
  user:{name:'Sanne de Vries',role:'Facilitair medewerker',location:'Amersfoort',sizes:'Boven L · Broek 40 · Schoen 43'},
  cart:[],
  products:[
    {id:1,name:'Facility Polo',points:15,cat:'Werkkleding',icon:'👕',size:'L'},
    {id:2,name:'Softshell jas',points:35,cat:'Werkkleding',icon:'🧥',size:'L'},
    {id:3,name:'Werkbroek',points:25,cat:'Werkkleding',icon:'👖',size:'40'},
    {id:4,name:'Veiligheidsschoenen S3',points:45,cat:'PBM',icon:'🥾',size:'43'},
    {id:5,name:'Werkhandschoenen',points:10,cat:'PBM',icon:'🧤',size:'L'},
    {id:6,name:'Veiligheidshelm',points:20,cat:'PBM',icon:'⛑️',size:'One size'},
    {id:7,name:'Sweater',points:20,cat:'Werkkleding',icon:'🧶',size:'L'},
    {id:8,name:'Regenjas',points:40,cat:'Werkkleding',icon:'🌧️',size:'L'},
    {id:9,name:'Bodywarmer',points:30,cat:'Werkkleding',icon:'🦺',size:'L'}
  ]
}
const app=document.querySelector('#app');
const money=n=>'€ '+n.toLocaleString('nl-NL');
function toast(msg){const t=document.createElement('div');t.className='toast';t.textContent=msg;document.body.appendChild(t);setTimeout(()=>t.remove(),2200)}
function go(route){state.route=route;render();window.scrollTo({top:0,behavior:'smooth'})}
function logo(){return `<div class="logo-box">FACILITY.</div>`}
function topbar(){return `<div class="topbar"><div class="topbar-inner"><div class="brand">${logo()}<small>Werkkleding & tools</small></div><div class="nav"><button onclick="go('landing')">Home</button><button onclick="go('catalog')">Werkkleding</button><button onclick="go('catalog')">PBM's</button><button onclick="go('tools')">Gereedschap</button><button onclick="go('how')">Hoe het werkt</button><button class="btn primary" onclick="go('login')">Inloggen</button></div></div></div>`}
function landing(){return `<div class="shell">${topbar()}<main class="container"><section class="hero"><div class="hero-grid"><div class="hero-copy"><div class="eyebrow">Facility medewerkersomgeving</div><h1>Jouw werkkleding, jouw omgeving.</h1><p>Bestel eenvoudig goedgekeurde bedrijfskleding en PBM's, vraag gereedschap aan en houd zelf inzicht in je persoonlijke budget en bestellingen.</p><div class="hero-actions"><button class="btn primary" onclick="go('login')">Naar mijn omgeving →</button><button class="btn outline" onclick="go('how')">Bekijk hoe het werkt</button></div></div><div class="hero-art"><div class="person-card"></div><div class="hero-tag">Samen voor een schone, veilige en fijne werkomgeving.</div></div></div></section><div class="feature-strip"><div class="feature"><div class="ico">👕</div><div><b>Werkkleding</b><span>Representatief en comfortabel</span></div></div><div class="feature"><div class="ico">⛑️</div><div><b>PBM's</b><span>Veilig aan het werk</span></div></div><div class="feature"><div class="ico">🛠️</div><div><b>Gereedschap</b><span>Aanvragen en beheren</span></div></div><div class="feature"><div class="ico">👤</div><div><b>Persoonlijk</b><span>Budget, maten en orders</span></div></div></div><div class="section-title"><div><h2>Alles in één Facility-omgeving</h2><p>RVE beheert achter de schermen het assortiment, de orders en fulfilment.</p></div></div><div class="grid cols-3"><div class="card"><h3>Persoonlijk assortiment</h3><p class="muted">Medewerkers zien alleen artikelen die bij hun functie en locatie horen.</p></div><div class="card"><h3>Budget & punten</h3><p class="muted">Facility stelt budgetten in; medewerkers zien direct wat nog beschikbaar is.</p></div><div class="card"><h3>Order naar RVE</h3><p class="muted">Na bestellen komt de order direct in het centrale RVE-ordercentrum terecht.</p></div></div></main>${footer()}</div>`}
function login(){return `<div class="login-page"><section class="login-art"><div>${logo()}<h1>Inloggen op jouw Facility omgeving</h1><p>Werkkleding, PBM's en gereedschap eenvoudig geregeld.</p></div><div class="mini">Deze demo is ontwikkeld als concept voor Facility × RVE Bedrijfskleding.</div></section><section class="login-panel"><div class="login-card"><h2>Welkom terug</h2><p class="muted">Gebruik de demo-knoppen om werknemer of beheerder te openen.</p><div class="field"><label>E-mailadres</label><input value="sanne@facility.nl"></div><div class="field"><label>Wachtwoord</label><input type="password" value="demo1234"></div><button class="btn primary" style="width:100%" onclick="state.mode='employee';go('dashboard')">Inloggen als medewerker</button><button class="btn dark" style="width:100%;margin-top:10px" onclick="state.mode='admin';go('admin')">Open Facility beheer</button><button class="ghost" style="width:100%;margin-top:8px" onclick="go('landing')">← Terug naar website</button></div></section></div>`}
function sidebar(active){const items=state.mode==='admin'?[['admin','Dashboard','◫'],['employees','Medewerkers','👥'],['catalog','Assortiment','👕'],['orders','Bestellingen','📦'],['tools','Gereedschap','🛠️'],['reports','Rapportages','📊']]:[['dashboard','Dashboard','◫'],['catalog','Werkkleding','👕'],['catalog','PBM’s','⛑️'],['tools','Gereedschap','🛠️'],['orders','Mijn bestellingen','📦'],['profile','Mijn profiel','👤']];return `<aside class="sidebar"><div class="side-logo">${logo()}</div><div class="side-nav">${items.map(i=>`<button class="${active===i[0]?'active':''}" onclick="go('${i[0]}')"><span>${i[2]}</span>${i[1]}</button>`).join('')}</div><div class="side-foot">Powered & fulfilled by <b>RVE Bedrijfskleding</b></div></aside>`}
function appFrame(active,content,title){return `<div class="shell">${topbar()}<div class="app-shell">${sidebar(active)}<main class="content"><div class="content-head"><div><div class="eyebrow">${state.mode==='admin'?'Facility beheer':'Medewerkersomgeving'}</div><h2>${title}</h2></div><div class="user-chip"><div class="avatar">${state.mode==='admin'?'FM':'SD'}</div><div><b>${state.mode==='admin'?'Facility Manager':state.user.name}</b><div class="mini">${state.mode==='admin'?'HR / Inkoop':state.user.role}</div></div></div></div>${content}</main></div></div>`}
function dashboard(){const recent=state.cart.length;return appFrame('dashboard',`<div class="grid cols-4"><div class="card"><div class="label">Jouw budget</div><div class="kpi">${state.points}</div><div class="mini">van 300 punten beschikbaar</div><div class="progress"><span style="width:${Math.min(100,state.points/3)}%"></span></div></div><div class="card"><div class="label">Openstaande orders</div><div class="kpi">2</div><div class="mini">1 wordt verwerkt door RVE</div></div><div class="card"><div class="label">Gereedschap op naam</div><div class="kpi">3</div><div class="mini">Alle assets zijn actief</div></div><div class="card"><div class="label">Nieuwe meldingen</div><div class="kpi">${recent}</div><div class="mini">Actuele winkelwagenitems</div></div></div><div class="section-title"><div><h2>Goedemorgen Sanne</h2><p>${state.user.role} · ${state.user.location}</p></div></div><div class="grid cols-3"><div class="card"><h3>👕 Werkkleding</h3><p class="muted">Polo's, jassen, broeken en meer.</p><button class="btn outline" onclick="go('catalog')">Bekijken</button></div><div class="card"><h3>⛑️ PBM's</h3><p class="muted">Veilig werken begint met de juiste middelen.</p><button class="btn outline" onclick="go('catalog')">Bekijken</button></div><div class="card"><h3>🛠️ Gereedschap</h3><p class="muted">Aanvragen en inzien wat aan jou is uitgegeven.</p><button class="btn outline" onclick="go('tools')">Bekijken</button></div></div><div class="section-title"><div><h2>Voor jou geselecteerd</h2><p>Op basis van je functie en persoonlijke maten.</p></div></div>${productCards(state.products.slice(0,3))}`, 'Mijn dashboard')}
function productCards(list){return `<div class="product-grid">${list.map(p=>`<div class="product"><div class="product-img">${p.icon}</div><div><div class="mini">${p.cat}</div><h4>${p.name}</h4><div class="mini">Maat ${p.size}</div></div><div class="row"><span class="price">${p.points} punten</span><button class="btn primary" onclick="addToCart(${p.id})">Bestellen</button></div></div>`).join('')}</div>`}
function catalog(){return appFrame('catalog',`<div class="card" style="margin-bottom:18px"><div class="grid cols-3"><div><div class="label">Assortiment</div><h3>Alleen voor jouw functie</h3></div><div class="field" style="margin:0"><label>Categorie</label><select id="cat" onchange="filterCat(this.value)"><option>Alles</option><option>Werkkleding</option><option>PBM</option></select></div><div class="field" style="margin:0"><label>Zoeken</label><input id="search" placeholder="Zoek artikel..." oninput="filterSearch(this.value)"></div></div></div><div id="products">${productCards(state.products)}</div><div class="card" style="margin-top:20px;display:flex;justify-content:space-between;align-items:center;gap:14px;flex-wrap:wrap"><div><b>${state.cart.reduce((a,b)=>a+b.qty,0)} artikelen in je winkelwagen</b><div class="mini">Totaal ${state.cart.reduce((a,b)=>a+b.points*b.qty,0)} punten</div></div><button class="btn dark" onclick="go('cart')">Naar winkelwagen →</button></div>`, 'Assortiment')}
function filterCat(cat){document.querySelector('#products').innerHTML=productCards(cat==='Alles'?state.products:state.products.filter(p=>p.cat===cat))}
function filterSearch(q){const v=q.toLowerCase();document.querySelector('#products').innerHTML=productCards(state.products.filter(p=>p.name.toLowerCase().includes(v)))}
function addToCart(id){const p=state.products.find(x=>x.id===id),ex=state.cart.find(x=>x.id===id);ex?ex.qty++:state.cart.push({...p,qty:1});toast(`${p.name} toegevoegd`);}
function cart(){const total=state.cart.reduce((a,b)=>a+b.points*b.qty,0);return appFrame('catalog',`<div class="grid cols-2"><div class="card"><h3>Mijn bestelling</h3>${state.cart.length?state.cart.map(p=>`<div class="cart-line"><div class="thumb">${p.icon}</div><div><b>${p.name}</b><div class="mini">Maat ${p.size}</div></div><div class="qty"><button onclick="qty(${p.id},-1)">−</button><b>${p.qty}</b><button onclick="qty(${p.id},1)">+</button></div><div class="price">${p.points*p.qty} pt</div></div>`).join(''):'<p class="muted">Je winkelwagen is nog leeg.</p>'}</div><div class="card"><h3>Samenvatting</h3><div class="row"><span>Huidig budget</span><b>${state.points} punten</b></div><div class="row"><span>Deze bestelling</span><b>${total} punten</b></div><hr style="border:0;border-top:1px solid var(--line);margin:18px 0"><div class="row"><span>Resterend</span><span class="kpi" style="font-size:28px">${state.points-total}</span></div><button class="btn primary" style="width:100%;margin-top:18px" ${!state.cart.length?'disabled':''} onclick="checkout()">Bestelling plaatsen →</button><p class="mini">Na plaatsen gaat de order rechtstreeks naar RVE Bedrijfskleding voor verwerking.</p></div></div>`, 'Winkelwagen')}
function qty(id,d){const p=state.cart.find(x=>x.id===id);if(!p)return;p.qty+=d;if(p.qty<=0)state.cart=state.cart.filter(x=>x.id!==id);render()}
function checkout(){const total=state.cart.reduce((a,b)=>a+b.points*b.qty,0);if(total>state.points){toast('Onvoldoende punten');return}state.points-=total;state.cart=[];toast('Bestelling doorgestuurd naar RVE');go('orders')}
function orders(){return appFrame('orders',`<div class="table-wrap"><table class="table"><thead><tr><th>Order</th><th>Datum</th><th>Artikelen</th><th>Status</th><th>Verwerking</th></tr></thead><tbody><tr><td><b>#FAC-10582</b></td><td>12-01-2026</td><td>Polo, werkbroek, schoenen</td><td><span class="status">Verzonden</span></td><td>RVE Bedrijfskleding</td></tr><tr><td><b>#FAC-10579</b></td><td>08-01-2026</td><td>Softshell jas</td><td><span class="status warn">In verwerking</span></td><td>RVE Bedrijfskleding</td></tr><tr><td><b>#FAC-10571</b></td><td>04-01-2026</td><td>Handschoenen</td><td><span class="status">Geleverd</span></td><td>RVE Bedrijfskleding</td></tr></tbody></table></div>`, state.mode==='admin'?'Bestellingen':'Mijn bestellingen')}
function tools(){const rows=[['Accuboormachine 18V','FAC-00481','In gebruik','Sanne de Vries'],['Multimeter','FAC-00192','In gebruik','Jan Jansen'],['Gereedschapskoffer','FAC-00321','Op voorraad','—'],['Zaklamp','FAC-00711','In gebruik','Peter Bakker'],['Steekwagen','FAC-00832','Ter reparatie','—']];return appFrame('tools',`<div class="grid cols-4"><div class="card"><div class="label">Alle tools</div><div class="kpi">184</div></div><div class="card"><div class="label">In gebruik</div><div class="kpi">142</div></div><div class="card"><div class="label">Op voorraad</div><div class="kpi">29</div></div><div class="card"><div class="label">Ter reparatie</div><div class="kpi">8</div></div></div><div class="section-title"><div><h2>Gereedschap</h2><p>Uitgifte, aanvragen en assetregistratie.</p></div><button class="btn primary" onclick="toast('Nieuwe gereedschapsaanvraag gestart')">+ Aanvragen</button></div><div class="table-wrap"><table class="table"><thead><tr><th>Product</th><th>Assetnummer</th><th>Status</th><th>Medewerker</th></tr></thead><tbody>${rows.map(r=>`<tr><td><b>${r[0]}</b></td><td>${r[1]}</td><td><span class="status ${r[2]==='Ter reparatie'?'danger':r[2]==='Op voorraad'?'warn':''}">${r[2]}</span></td><td>${r[3]}</td></tr>`).join('')}</tbody></table></div>`, 'Gereedschap')}
function profile(){return appFrame('profile',`<div class="grid cols-2"><div class="card"><h3>Persoonlijke gegevens</h3><div class="field"><label>Naam</label><input value="${state.user.name}"></div><div class="field"><label>Functie</label><input value="${state.user.role}"></div><div class="field"><label>Locatie</label><input value="${state.user.location}"></div></div><div class="card"><h3>Maten</h3><p class="muted">Deze maten worden standaard gebruikt bij geschikte artikelen.</p><div class="field"><label>Bovenkleding</label><select><option>L</option></select></div><div class="field"><label>Broekmaat</label><select><option>40</option></select></div><div class="field"><label>Schoenmaat</label><select><option>43</option></select></div><button class="btn primary" onclick="toast('Profiel opgeslagen')">Opslaan</button></div></div>`, 'Mijn profiel')}
function admin(){return appFrame('admin',`<div class="grid cols-4"><div class="card"><div class="label">Medewerkers</div><div class="kpi">350</div><div class="mini">337 actief</div></div><div class="card"><div class="label">Openstaande bestellingen</div><div class="kpi">12</div><div class="mini">5 vandaag</div></div><div class="card"><div class="label">Gereedschapsaanvragen</div><div class="kpi">8</div><div class="mini">3 goedkeuring nodig</div></div><div class="card"><div class="label">Budget gebruikt</div><div class="kpi">47%</div><div class="mini">van € 87.500</div></div></div><div class="grid cols-2" style="margin-top:18px"><div class="card"><h3>Budgetverbruik</h3><div class="kpi" style="font-size:28px">${money(87500)}</div><div class="progress"><span style="width:47%"></span></div><div style="margin-top:18px" class="mini">Werkkleding ${money(24850)} · PBM's ${money(8400)} · Gereedschap ${money(7100)} · Overig ${money(900)}</div></div><div class="card"><h3>Recente activiteiten</h3><p><b>Sanne de Vries</b><br><span class="mini">Bestelling geplaatst · vandaag 10:24</span></p><p><b>Jan Jansen</b><br><span class="mini">Gereedschapsaanvraag · vandaag 09:12</span></p><p><b>Lisa Smit</b><br><span class="mini">Bestelling geleverd · gisteren 14:20</span></p></div></div><div class="section-title"><div><h2>RVE orderkoppeling</h2><p>Facility ziet status; RVE verwerkt centraal.</p></div></div>${flow()}`, 'Dashboard')}
function employees(){return appFrame('employees',`<div class="card" style="margin-bottom:18px"><div style="display:flex;gap:12px;justify-content:space-between;flex-wrap:wrap"><input style="flex:1;min-width:240px;border:1px solid var(--line);border-radius:12px;padding:12px" placeholder="Zoek medewerker"><button class="btn primary" onclick="toast('Medewerker toevoegen')">+ Medewerker toevoegen</button></div></div><div class="table-wrap"><table class="table"><thead><tr><th>Naam</th><th>Functie</th><th>Locatie</th><th>Punten</th><th>Status</th></tr></thead><tbody><tr><td>Sanne de Vries</td><td>Facilitair medewerker</td><td>Amersfoort</td><td>220</td><td><span class="status">Actief</span></td></tr><tr><td>Jan Jansen</td><td>Huismeester</td><td>Amersfoort</td><td>145</td><td><span class="status">Actief</span></td></tr><tr><td>Peter Bakker</td><td>Technische dienst</td><td>Amersfoort</td><td>310</td><td><span class="status">Actief</span></td></tr><tr><td>Lisa Smit</td><td>Servicedesk</td><td>Utrecht</td><td>180</td><td><span class="status">Actief</span></td></tr></tbody></table></div>`, 'Medewerkers')}
function reports(){return appFrame('reports',`<div class="grid cols-3"><div class="card"><div class="label">Orders dit jaar</div><div class="kpi">684</div><div class="mini">+12% t.o.v. vorig jaar</div></div><div class="card"><div class="label">Gem. punten per medewerker</div><div class="kpi">118</div><div class="mini">per jaar gebruikt</div></div><div class="card"><div class="label">Leverbetrouwbaarheid</div><div class="kpi">96%</div><div class="mini">demo-indicator</div></div></div><div class="section-title"><div><h2>Rapportages</h2><p>Budget, assortiment, gebruik en orderstatus in één overzicht.</p></div></div><div class="card"><h3>Exportmogelijkheden</h3><p class="muted">In een productieversie kunnen rapporten geëxporteerd worden naar Excel/CSV en gekoppeld worden aan HR- of ERP-systemen.</p><button class="btn outline" onclick="toast('Demo-export voorbereid')">Exporteer rapport</button></div>`, 'Rapportages')}
function how(){return `<div class="shell">${topbar()}<main class="container"><div class="section-title"><div><div class="eyebrow">Facility × RVE</div><h2>Van bestelling tot levering</h2><p>De medewerker bestelt in Facility-huisstijl. RVE verzorgt de uitvoering.</p></div></div>${flow()}<div class="section-title"><div><h2>Wie doet wat?</h2></div></div><div class="grid cols-3"><div class="card"><h3>Facility</h3><p class="muted">Beheert medewerkers, functies, budgetten, assortimentrechten en goedkeuringen.</p></div><div class="card"><h3>Medewerker</h3><p class="muted">Bestelt goedgekeurde kleding/PBM en vraagt gereedschap aan.</p></div><div class="card"><h3>RVE Bedrijfskleding</h3><p class="muted">Ontvangt orders, beheert producten/voorraad, personaliseert, verpakt, verzendt en factureert.</p></div></div><div style="margin-top:28px"><button class="btn dark" onclick="go('login')">Open demo →</button></div></main>${footer()}</div>`}
function flow(){return `<div class="order-flow"><div class="flow-step"><div class="flow-no">1</div><b>Medewerker bestelt</b><small>Via de Facility omgeving</small></div><div class="flow-step"><div class="flow-no">2</div><b>Order naar RVE</b><small>Automatisch in ordercentrum</small></div><div class="flow-step"><div class="flow-no">3</div><b>Verwerking</b><small>Voorraad, bedrukken, verpakken</small></div><div class="flow-step"><div class="flow-no">4</div><b>Verzending</b><small>Naar medewerker of locatie</small></div><div class="flow-step"><div class="flow-no">5</div><b>Levering</b><small>Status terug in Facility</small></div></div>`}
function footer(){return `<footer class="footer"><div class="footer-inner"><div class="brand">${logo()}<span>×</span><div class="logo-box">RVE</div></div><div><b>Mogelijk gemaakt door RVE Bedrijfskleding</b><div class="mini">Partner voor bedrijfskleding, PBM's en gereedschap.</div></div></div></footer>`}
function render(){switch(state.route){case'landing':app.innerHTML=landing();break;case'login':app.innerHTML=login();break;case'dashboard':state.mode='employee';app.innerHTML=dashboard();break;case'catalog':app.innerHTML=catalog();break;case'cart':app.innerHTML=cart();break;case'orders':app.innerHTML=orders();break;case'tools':app.innerHTML=tools();break;case'profile':app.innerHTML=profile();break;case'admin':state.mode='admin';app.innerHTML=admin();break;case'employees':state.mode='admin';app.innerHTML=employees();break;case'reports':state.mode='admin';app.innerHTML=reports();break;case'how':app.innerHTML=how();break;default:app.innerHTML=landing()}}
window.go=go;window.addToCart=addToCart;window.qty=qty;window.checkout=checkout;window.filterCat=filterCat;window.filterSearch=filterSearch;window.toast=toast;
render();
